core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('entrepreneurs/', include('entrepreneurs.urls')),
    path('investors/', include('investors.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('suggestions/', views.suggestions, name='suggestions'),
    path('company/<int:pk>', views.see_company, name='see_company'),
    path('company/<int:pk>/propose/', views.propose, name='propose'),
    path('contract/<int:pk>/', views.contract, name='contract'),
]

entrepreneurs/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import (
    FileExtensionValidator,
    MinLengthValidator,
    MinValueValidator,
    validate_image_file_extension,
)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.utils.safestring import mark_safe
from utils.entrepreneurs.model_messages import CompanyMessages, DocumentMessages


def now_date():
    return timezone.now().date()


class Company(models.Model):
    class TimeOfExistenceChoices(models.TextChoices):
        """time of existence of the company"""
        LESS_6M = '-6', _('Menos de 6 meses')
        GREATEST_6M = '+6', _('Mais de 6 meses')
        GREATEST_1Y = '+1', _('Mais de 1 ano')
        GREATEST_5Y = '+5', _('Mais de 5 anos')
    
    class StageChoices(models.TextChoices):
        """the atual stage of the company"""
        IDEA = 'I', _('Tenho apenas uma idea')
        MVP = 'MVP', _('Possuo um MVP')
        MVPP = 'MVPP', _('Possuo um MVP com clientes pagantes')
        SCALABLE = 'E', _('Empresa pronta para escalar')
    
    class AreaChoices(models.TextChoices):
        """the area of actuation of the company"""
        ED_TECH = 'ED', _('Ed-tech')
        FIN_TECH = 'FT', _('Fintech')
        AGRO_TECH = 'AT', _('Agrotech')
    
    class TargetAudienceChoices(models.TextChoices):
        """the target audience which the company has interest"""
        B2B = 'B2B'
        B2C = 'B2C'

    user = models.ForeignKey(
        User, 
        on_delete=models.DO_NOTHING, 
        verbose_name='Usuário',
        null=False,
        blank=False,
        error_messages={
            'blank': CompanyMessages.EMPTY_NAME,
            'null': CompanyMessages.EMPTY_NAME,
            'invalid': CompanyMessages.INVALID_USER
        }
    )
    name = models.CharField(
        'Nome', 
        max_length=50,
        null=False,
        blank=False,
        unique=True,
        error_messages={
            'null': CompanyMessages.EMPTY_NAME,
            'blank': CompanyMessages.EMPTY_NAME,
            'invalid': CompanyMessages.INVALID_NAME,
            'unique': CompanyMessages.DUPLICATED_NAME
        }
    )
    cnpj = models.CharField(
        'CNPJ',
        max_length=30,
        null=False,
        blank=False,
        unique=True,
        error_messages={
            'unique': CompanyMessages.DUPLICATED_CNPJ,
            'null': CompanyMessages.EMPTY_CNPJ,
            'blank': CompanyMessages.EMPTY_CNPJ,
            'invalid': CompanyMessages.INVALID_CNPJ
        }
    )
    site = models.URLField(
        'Site',
        unique=True,
        blank=False,
        null=False,
        error_messages={
            'unique': CompanyMessages.DUPLICATED_SITE,
            'invalid': CompanyMessages.INVALID_SITE,
            'blank': CompanyMessages.EMPTY_SITE,
            'null': CompanyMessages.EMPTY_SITE,
        }
    )
    time_of_existence = models.CharField(
        'Tempo de existência',
        max_length=2,
        choices=TimeOfExistenceChoices.choices,
        default=TimeOfExistenceChoices.LESS_6M,
        null=False,
        blank=False,
        error_messages={
            'invalid': CompanyMessages.INVALID_TIME_OF_EXISTENCE,
            'null': CompanyMessages.EMPTY_TIME_OF_EXISTENCE,
            'blank': CompanyMessages.EMPTY_TIME_OF_EXISTENCE,
        }
    )
    desc = models.TextField(
        'Descrição',
        error_messages={
            'null': CompanyMessages.EMPTY_DESC,
            'blank': CompanyMessages.EMPTY_DESC,
        }
    )
    final_date_capitation = models.DateField(
        'Data final de capitação',
        null=False,
        blank=False,
        validators=[
            MinValueValidator(now_date, CompanyMessages.INVALID_FINAL_DATE_CAPITATION)
        ],
        error_messages={
            'invalid': CompanyMessages.INVALID_FINAL_DATE_CAPITATION,
            'blank': CompanyMessages.EMPTY_FINAL_DATE_CAPITATION,
        }
    )
    percent_equity = models.IntegerField(
        'Percentual Equity',
        null=False,
        blank=False,
        error_messages={
            'invalid': CompanyMessages.INVALID_PERCENT_EQUITY,
            'null': CompanyMessages.EMPTY_PERCENT_EQUITY,
            'blank': CompanyMessages.EMPTY_PERCENT_EQUITY,
        }
    )
    stage = models.CharField(
        'Estagio',
        max_length=4,
        choices=StageChoices.choices,
        default=StageChoices.IDEA,
        null=False,
        blank=False,
        error_messages={
            'invalid': CompanyMessages.INVALID_STAGE,
            'null': CompanyMessages.EMPTY_STAGE,
            'blank': CompanyMessages.EMPTY_STAGE,
        }
    )
    area = models.CharField(
        max_length=3,
        choices=AreaChoices.choices,
        default=AreaChoices.AGRO_TECH,
        null=False,
        blank=False,
        error_messages={
            'invalid': CompanyMessages.INVALID_AREA,
            'blank': CompanyMessages.EMPTY_AREA,
            'null': CompanyMessages.EMPTY_AREA,
        }
    )
    target_audience = models.CharField(
        'Publico alvo',
        max_length=3,
        choices=TargetAudienceChoices.choices,
        default=TargetAudienceChoices.B2B,
        null=False,
        blank=False,
        error_messages={
            'invalid': CompanyMessages.INVALID_TARGET_AUDIENCE,
            'null': CompanyMessages.EMPTY_TARGET_AUDIENCE,
            'blank': CompanyMessages.EMPTY_TARGET_AUDIENCE,
        }
    )
    value = models.DecimalField(
        'Valor de capitação',
        max_digits=9,
        decimal_places=2,
        null=False,
        blank=False,
        validators=[
            MinValueValidator(0, CompanyMessages.INVALID_VALUE)
        ],
        error_messages={
            'invalid': CompanyMessages.INVALID_VALUE,
            'blank': CompanyMessages.EMPTY_VALUE,
            'null': CompanyMessages.EMPTY_VALUE,
        }
    )
    pitch = models.FileField(
        upload_to='pitchs',
        validators=[
            FileExtensionValidator(['wav', 'mp4'])
        ],
        null=True,
        blank=True
    )
    logo = models.FileField(
        upload_to='logos',
        null=False,
        blank=False,
        validators=[
            validate_image_file_extension
        ],
        error_messages={
            'null': CompanyMessages.EMPTY_LOGO,
            'blank': CompanyMessages.EMPTY_LOGO,
        }
    )

    def  __str__(self):
        return f'{self.user.username} | {self.name}'
    
    def clean(self) -> None:
        super().clean()
        self.error_messages = {}
        PITCH_MAX_MB = 50
        LOGO_MAX_MB = 5
        if not self._validate_cnpj(self.cnpj):
            raise ValidationError({'cnpj': CompanyMessages.INVALID_CNPJ})
        
        elif self.pitch and self._validate_file_size(self.pitch, max_MB=PITCH_MAX_MB):
            msg = CompanyMessages.INVALID_FILE_SIZE.format_map({'field': 'pitch', 'size': f'{PITCH_MAX_MB}MB'})
            raise ValidationError({'pitch': msg})
        
        elif self.logo and self._validate_file_size(self.logo, max_MB=LOGO_MAX_MB):
            msg = CompanyMessages.INVALID_FILE_SIZE.format_map({'field': 'logo', 'size': f'{LOGO_MAX_MB}MB'})
            raise ValidationError({'logo': msg})
    
    @staticmethod
    def _validate_cnpj(cnpj: str) -> bool:
        """the function to validate if the CNPJ of the company is valid

        Args:
            cnpj (str): the company CNPJ to validate

        Returns:
            bool: True if the given CNPJ is valid
        
        Examples:
        >>> Company._validate_cnpj('24.040.568/0001-02)
        >>> True
        >>> Company._validate_cnpj('24040568000102)
        >>> True
        >>> Company._validate_cnpj('11111111111111')
        >>> False
        """
        cnpj = ''.join(filter(str.isdigit, cnpj))

        if len(cnpj) != 14:
            return False

        if cnpj in (c * 14 for c in "1234567890"):
            return False

        def calc_digito(cnpj, digit):
            if digit == 1:
                weight = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
            elif digit == 2:
                weight = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]

            sum_ = sum(int(cnpj[i]) * weight[i] for i in range(len(weight)))
            rest = sum_ % 11
            return 0 if rest < 2 else 11 - rest

        if calc_digito(cnpj[:12], 1) != int(cnpj[12]):
            return False
        if calc_digito(cnpj[:13], 2) != int(cnpj[13]):
            return False

        return True

    @staticmethod
    def _validate_file_size(file_field, max_MB=50):
        """validate the file size with considering the MB unit
        Args:
            image (Any): the file field with support to property `size`.
            max_MB (int, Optional): the max size in MB that the file can have. Defaults to 50MB
        
        Returns:
            bool: True if the file size is less or equal than `max_MB` else False

        Example:
        >>> my_company = Company.objects.first()
        >>> my_company.pitch.size 
        >>> 10240  # 10MB
        >>> Company._validate_image_size(my_company.pitch, max_MB=10)
        >>> True
        """
        max_ = max_MB * 1024
        return False if file_field.size > max_ else True

    @property
    def status(self) -> str:
        if timezone.now().date() > self.final_date_capitation:
            return mark_safe('<span class="badge bg-success">Finalizada</span>')
        return mark_safe('<span class="badge bg-primary">Disponível</span>')

    @property
    def valuation(self):
        val = f'{100 * self.value / self.percent_equity:.2f}'
        return val

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'


class Document(models.Model):
    company = models.ForeignKey(
        Company, 
        on_delete=models.DO_NOTHING,
        verbose_name='Empresa',

investors/views.py
from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpRequest, Http404
from entrepreneurs.models import Company, Document, Metric
from django.contrib import messages
from django.db.models import F, Q
from django.core.exceptions import ValidationError
from .models import ProposalInvestment
from django.db.models.aggregates import Sum
from utils.supportfuncs import cast


def suggestions(request: HttpRequest):
    """show and filter suggestions of companies to invest"""
    areas = Company.AreaChoices
    if request.method == "GET":   
        return render(request, 'suggestions.html', {'areas': areas})
    
    elif request.method == "POST":
        type_ = request.POST.get('tipo')
        area = request.POST.getlist('area_')
        value = request.POST.get('valor')

        qs = Company.objects
        qs_dict = {
            'C': qs.filter(
                Q(time_of_existence=Company.TimeOfExistenceChoices.GREATEST_5Y)|
                Q(stage=Company.StageChoices.SCALABLE)
            ),
            'I': qs.filter(
                time_of_existence__in=[
                    Company.TimeOfExistenceChoices.GREATEST_6M,
                    Company.TimeOfExistenceChoices.GREATEST_1Y,
                ],
            ).exclude(stage=Company.StageChoices.IDEA),
            'D': qs.exclude(
                Q(time_of_existence=Company.TimeOfExistenceChoices.GREATEST_5Y)|
                Q(stage=Company.StageChoices.SCALABLE)
            ),
        }
        if type_ not in qs_dict.keys():
            messages.error(request, 'Tipo de perfil selecionado é inválido.')
            return redirect('suggestions')
        
        qs = qs_dict[type_]
        print(area)
        qs = qs.filter(area__in=area)
        
        selected_companies = qs.annotate(
            val=100 * F('value') / F('percent_equity'),
            pct=Decimal(value) * 100 / F('val')
        ).filter(pct__gte=1)
        
        return render(request, 'suggestions.html', {'companies': selected_companies, 'areas': areas})


def see_company(request: HttpRequest, pk: int):
    """shows the page of the company with information to the investor"""
    company = get_object_or_404(Company, pk=pk)
    company_summary = ProposalInvestment.get_summary(company)
    sold_pct = company_summary.get('sold_pct')

    limiar = 80 * company.percent_equity / 100
    context = {
        'company': company,
        'docs': Document.objects.filter(company=company),
        'metrics': Metric.objects.filter(company=company),
        'sold_pct': int(sold_pct),
        'concretized': True if sold_pct >= limiar else False,
        'pct_available': company.percent_equity - int(sold_pct)
    }
    return render(request, 'see_company.html', context)


def propose(request: HttpRequest, pk: int):
    """receives an user's proposal and save it in the DB"""
    REDIRECT = redirect(reverse('see_company', args=[pk]))

    company = get_object_or_404(Company, pk=pk)
    value = cast(request.POST.get('valor'), int)
    percent = cast(request.POST.get('percentual'), int)

    if not all((value, percent)):
        messages.error(request, 'Há campos inválidos ou não preenchidos.')
        return REDIRECT
    
    proposal_valuation = value * 100 / percent
    min_available_valuation = float(company.valuation) // 2

    if proposal_valuation < min_available_valuation:
        messages.error(request, f'O valuation mínimo é de {min_available_valuation}. Recebido: {proposal_valuation}')
        return REDIRECT

    tot_pct = ProposalInvestment.objects.filter(
        company=company, status=ProposalInvestment.ProposalStatus.ACCEPTED
    ).aggregate(
        pct_sum=Sum('percent', default=0)
    ).get('pct_sum')

    available_pct = int(company.percent_equity - tot_pct)
    if percent > available_pct:
        messages.warning(
            request, f'Valor de porcentagem disponível para esta empresa é de {available_pct}%'
        )
        return REDIRECT
    
    proposal = ProposalInvestment(
        value=value,
        percent=percent,
        company=company,
        investor=request.user
    )

    try:
        proposal.full_clean()
    except ValidationError as exc:
        messages.error(request, exc.messages[0])
        return REDIRECT

    proposal.save()
    messages.success(request, 'Proposta enviada.')
    return REDIRECT


def contract(request: HttpRequest, pk: int):
    """requests to the user a selfie and document photo to validate
    the contract of the proposal investment
    """
    proposal = get_object_or_404(ProposalInvestment, pk=pk)
    if proposal.status != proposal.ProposalStatus.WAITING:
        raise Http404()
    
    if request.method == 'GET':
        return render(request, 'contract.html', {'proposal': proposal})
    
    elif request.method == "POST":
        selfie = request.FILES.get('selfie')
        rg = request.FILES.get('rg')

        proposal.selfie = selfie
        proposal.rg = rg
        
        # TODO: criar modelo para validar se foto do tg coincide com selfie
        
        proposal.status = proposal.ProposalStatus.SENT
        proposal.save()

        messages.success(request, f'Contrato assinado com sucesso, sua proposta foi enviada a empresa.')
        return redirect(reverse('see_company', args=[proposal.company.pk]))

investors/templates/contract.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'entrepreneurs/css/list_company.css' %}">
<link rel="stylesheet" href="{% static 'entrepreneurs/css/company.css' %}">
<link rel="stylesheet" href="{% static 'users/css/users.css' %}">

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/_nav.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% include "partials/_messages.html" %}
                    <div class="col-md-3">
                        <img src="{{proposal.company.logo.url}}" class="foto-empresa img-fluid" alt="">
                    </div>
                    <div class="col-md">
                        <h3>Assinar contrato</h3>
                    </div>
                    
                </div>    
        </div>
        <div style="margin-top: 40px; padding: 20px" class="contrato dark-color">
            <h3>Contrato de investimento</h3>
            <p>Ao assinar esse contrato você concorda com todas as cláusulas abaixo</p>
            
            <ol>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
            </ol>

        </div>
        <form action="{% url 'contract' proposal.pk %}" enctype='multipart/form-data' method="POST" style="margin-top: 20px;"> {% csrf_token %}
            <input type="file" name="selfie" class="form-control" style="width: 40%">
            <br>
            <input type="file" name="rg" class="form-control" style="width: 40%">
            <br>
            <input type="submit" class="btn btn-indigo-normal" value="Assinar contrato">
        </form>
    </div>
    <br><br>
{% endblock 'body' %}

investors/templates/see_company.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

	<link rel="stylesheet" href="{% static 'entrepreneurs/css/list_company.css' %}">
	<link rel="stylesheet" href="{% static 'entrepreneurs/css/company_detail.css' %}">
	<link rel="stylesheet" href="{% static 'users/css/users.css' %}">
	
{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/_nav.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% include "partials/_messages.html" %}
                    <div class="col-md-3">
                        <img src="{{company.logo.url}}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-md">
                        <h3>{{company.name}}</h3>
                        <span class="badge bg-primary">{{company.get_area_display}}</span>
                    </div>
                    
                </div>
                <br><br>
                <div class="progress">
                    <div class="progress-bar bg-success"
                                style="width: {{sold_pct}}%"></div>

                            <div class="progress-bar bg-primary"
                             style="width: {{company.percent_equity}}%"></div>
                </div>
                <br>
                {% if concretized %}
                    <span class="badge bg-success">V</span><span>&nbsp &nbsp A empresa já atingiu 80% do percentual captado, portanto seu investimento será concretizado.</span>
                
                {% else %}
                    <span class="badge bg-warning">x</span><span>&nbsp &nbsp Seu investimento será concretizado caso a empresa atinja pelo meno 80% do valor esperado até a data final.</span>
                {% endif %}
                
                
                <hr>
                <p>{{company.desc}}</p>
                <div class="col-md">
                    <h5>Valuation esperado</h5>
                    <span class="sub-fonte">Esperado: R$ {{company.valuation}}</span>
                    <br>
                    <br>
                    <h5>Percentual</h5>
                    <span class="sub-fonte">Total a venda: {{company.percent_equity}}%</span>
                    <br>
                    <span class="sub-fonte">Disponivel à compra: {{pct_available}}%</span>
                </div>
                <br>
                <span class="badge bg-warning">{{company.target_audience}}</span>
                <br><br>
                <h4 style="color: #92D5EB">Indicadores |</h4>
                
                <div class="row">
                    {% for metric in metrics %}
                        <div class="col-md-3" >
                            <div class="dark-color" style="padding: 20px; text-align: center;">
                                <h5>{{metric.title|title}}</h5>
                                <h6>R$ {{metric.value}}</h6>
                            </div>
                        </div>
                    {% endfor %}

                    
                  
                </div>

                <hr>
                <div class="row">
                    <h4>Faça sua proposta</h4>
                    <br><br>
                    <div class="col-md">
                        <form action="{% url "propose" company.pk %}" method="POST"> {% csrf_token %}
                            <input type="number" name="valor" class="form-control" placeholder="Valor para investir">
                            <br>
                            <input type="submit" class="btn btn-indigo-normal" value="Salvar">
                    </div>
                    <div class="col-md">
                            <input type="number" name="percentual" class="form-control" placeholder="Percentual desejado">
                        </form>
                    </div>
                    
                </div>
            </div>
            <div class="col-md-5 intereses-investimentos">
                {% if company.pitch %}
                    <video name='demo' controls  width='100%'>
                        <source src="{{company.pitch.url}}" type="video/mp4"></source>
                    </video>
                {% endif %}

                <hr>
               
                {% for doc in docs %}
                    <div class="list_documentos">
                        <div class="row">
                            <div class="col-md-2" style="text-align: center">
                                <a href="{{doc.file.url}}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" style="color: white;" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                                    </svg>
                                </a>
                                
                            </div>
                            <div class="col-md-6">{{doc.title}}</div>
                            <div class="col-md-4" style="text-align: right;">
                                
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <br><br>
{% endblock 'body' %}

investors/templates/suggestions.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'entrepreneurs/css/list_companies.css' %}">
<link rel="stylesheet" href="{% static 'entrepreneurs/css/company_detail.css' %}">
<link rel="stylesheet" href="{% static 'users/css/users.css' %}">
<link rel="stylesheet" href="{% static 'investors/css/investors.css' %}">

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/_nav.html" %}
    <br><br>
    <div class="container">
        <div class="centralizar">
            <h2>Receba sugestões de empresas</h2>
            <p>Vamos analisar seu perfil e indicar as melhores opções de investimentos</p>
        </div>
        <br>
        <div class="dark-color cont-sugestao">
            <h3>Tipo de investidor</h3>
            <div style="width: 60%">
                <form action="{% url 'suggestions' %}" method="POST">{% csrf_token %}
                    {% include "partials/_messages.html" %}
                    <p>Selecione conservador caso busque investimentos de menos risco
                        e com menor retorno, selecione despojado se prefere correr mais riscos
                        e ter maiores possíbilidades de retorno.</p>
                    <select name="tipo" id="" class="form-select">
                        <option value="C">Conservador</option>
                        <option value="I">Intermediário</option>
                        <option value="D">Despojado</option>
                    </select>
                    <br>
                    <h3>Áreas de interesses</h3>
                    <p>Selecione as áreas de mercado que possui interesse em investir</p>
                    <select name="area_" id="" class="form-select" multiple>
                        {% for area in areas %}
                            <option value="{{area}}">{{area.label}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <h3>Valor que deseja investir</h3>
                    <p>Coloque o valor máximo que deseja investir</p>
                    <input type="number" name="valor" class="form-control" placeholder="00,00">
                    <br>
                    <input type="submit" class="btn btn-indigo">
                </form>
            </div>
            
        </div>

        <br>
        <br>

        <div class="row">
            {% for company in companies %}
                <div class="col-md">
                    <div class="card dark-color" style="width: 18rem; border: none;" >
                        <img class="card-img-top dark-color" src="{{company.logo.url}}" alt="Card image cap">
                        <div class="card-body dark-color">
                        <h5 class="card-title">{{company.name}}</h5>
                        <p class="card-text">{{company.desc}}</p>
                        <a href="{% url "see_company" company.pk %}" class="btn btn-indigo">Acessar</a>
                        </div>
                    </div>
                </div>
            
            {% empty %}
                <div class="col-md">
                    <h6>
                        Não encontramos nenhuma empresa com os filtros selecionados.
                    </h6>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock 'body' %}